---
title: "Store sales data"
format: html
editor: visual
---

Reading data from excel file
```{r}
library(tidyverse)
library (readxl)
library (ggcharts)
store_data <- read_excel("US Superstore data.xls",
                         .name_repair = function(nm) str_replace_all(nm, "[ -]", "_"))
store_data

```
Creating factors for categrorical vars 
```{r}
store_data <- store_data |>
 mutate(Ship_Mode = as.factor(Ship_Mode),
   Segment = as.factor(Segment),
   City = as.factor(City),
   State = as.factor(State),
   Region = as.factor(Region),
   Category = as.factor(Category),
   Sub_Category = as.factor(Sub_Category)) |>
  rename(Sell_Price = Sales)
store_data
```

Creating one way contingency table
```{r}
table(store_data$Segment)

```
Creating two way contingency table
```{r}
table (store_data$Segment, store_data$Region)

```
Numerical variables

```{r}
summary <- store_data |>
  group_by(year(Order_Date), State, Segment, Category) |>
  summarize(across(c(Profit, Sell_Price), .fns = list( "sum" = sum, "mean" = mean,
                                                         "median" = median,
                                                         "min" = min ,
                                                         "max" = max),
 .names = "{.fn}_{.col}"))
summary |> view()

#store_data |>
#  group_by(State, Segment, Category, Sub_Category) 

```

Functions for creating  graph
```{r}
#bar_chart <- function(year, state)
# Products having higest discount
fl <- "Segment"
ggplot(data=store_data, 
       aes(x = year(Order_Date), fill = !!sym(fl))) +
  geom_bar(width = 0.5) +
  labs(x = "Order Year", y = "Count", title = "Segment count by year")
```

```{r}
ggplot(data = store_data  |>
         filter(Profit > 0), 
       aes(x = month(Order_Date, label = TRUE), y = Profit, fill = Category)) +
  geom_col(alpha = 0.7) +
  facet_wrap(vars(year(Order_Date))) +
  theme(axis.text.x = element_text(angle =45, vjust = 0.6)) +
  labs(x = "", y = "Profit", title = "Profit per month for category")
```
```{r}
ggplot(data = store_data  |>
         filter(Profit < 0), 
       aes(x = month(Order_Date, label = TRUE), y = Profit, fill = Category)) +
  geom_col(alpha = 0.7) +
  facet_wrap(vars(year(Order_Date))) +
  theme(axis.text.x = element_text(angle =45, vjust = 0.6)) +
  labs(x = "", y = "Profit", title = "Loss per month for category")

```
line Graph
```{r}
ggplot(data = store_data, 
       mapping = aes(x= Category, y = Profit, fill= Category))+
  geom_boxplot() +
  coord_cartesian(ylim = c(-2000, 2000)) +
  labs(title = "Boxplot for Profit per Category")

```
```{r}
ggplot(data = store_data, 
       mapping = aes(x= Sub_Category, y = Profit, fill= Sub_Category))+
  geom_boxplot() +
  coord_cartesian(ylim = c(-2000, 2000)) +
  labs(title = "Boxplot for profit per Sub-category", x= "Product Sub-Category") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.6)) 
```
```{r}
# Comparing total profit vs total selling price for product categories
profit_data <- store_data |>
  group_by(year(Order_Date), Category) |>
  summarize(across(c(Profit, Sell_Price), .fns = list( "sum" = sum),
  .names = "{.fn}_{.col}")) |>
  rename(Year = `year(Order_Date)`)

ggplot(data= profit_data, aes(x =Year)) +
  geom_line(aes(y = sum_Profit/100 , col ="Total Profit")) +
  geom_line(aes(y = sum_Sell_Price/100, col = "Total Selling Price")) +
  geom_point(aes(y = sum_Profit/100)) +
  geom_point(aes(y = sum_Sell_Price/100)) +
  facet_grid(vars(Category)) +
  labs(title="Trend for Profit and Selling price", x = "Year", y = "USD(x100)")

```


 


